### ISSUE TITLE
opendkim/opendkim.c:dkimf_securefile: protect by mutex reading output of getpwuid

### ISSUE THREAD

**Issue by dilyanpalauzov** [trusteddomainproject/OpenDKIM#8]
`pw->pw_name` can be changed by a concurrent call of `getpwuid()`, so reading `pw->pw_name` it must be protected by the same lock, that protects `getpwuid()`.

Copy of https://sourceforge.net/p/opendkim/patches/39/.
```diff
diff --git a/opendkim/opendkim.c b/opendkim/opendkim.c
--- a/opendkim/opendkim.c
+++ b/opendkim/opendkim.c
@@ -4724,10 +4724,9 @@ dkimf_securefile(const char *path, ino_t *ino, uid_t myuid, char *err,
        if (myuid == (uid_t) -1)
                myuid = pw->pw_uid;
 
-       pthread_mutex_unlock(&pwdb_lock);
-
 #ifdef HAVE_REALPATH
        strlcpy(myname, pw->pw_name, sizeof myname);
+       pthread_mutex_unlock(&pwdb_lock);
 
        p = realpath(path, real);
        if (p == NULL)
@@ -4766,6 +4765,7 @@ dkimf_securefile(const char *path, ino_t *ino, uid_t myuid, char *err,
 
        return 1;
 #else /* HAVE_REALPATH */
+       pthread_mutex_unlock(&pwdb_lock);
        struct stat s;
 
        status = stat(path, &s);
```

**Comment by pgd151** [comment]
+patch

checkout

	opendkim git/develop

apply patch

	cat ../opendkim-test.patch
		--- opendkim.ORIG/opendkim/opendkim.c	2018-10-31 19:33:55.657887787 -0700
		+++ opendkim/opendkim/opendkim.c	2018-10-31 19:36:02.346814583 -0700
		@@ -4732,10 +4732,9 @@
			if (myuid == (uid_t) -1)
				myuid = pw->pw_uid;

		-	pthread_mutex_unlock(&pwdb_lock);
		-
		 #ifdef HAVE_REALPATH
			strlcpy(myname, pw->pw_name, sizeof myname);
		+	pthread_mutex_unlock(&pwdb_lock);

			p = realpath(path, real);
			if (p == NULL)
		@@ -4774,6 +4773,7 @@

			return 1;
		 #else /* HAVE_REALPATH */
		+	pthread_mutex_unlock(&pwdb_lock);
			struct stat s;

			status = stat(path, &s);
		@@ -5905,7 +5905,6 @@
		 dkimf_config_free(struct dkimf_config *conf)
		 {
			assert(conf != NULL);
		-	assert(conf->conf_refcnt == 0);

			dkimf_zapkey(conf);

	patch -p1 < ../opendkim-test.patch
		patching file opendkim/opendkim.c

launch daemon

after ~25 minutes, segfault

```
ls -al /var/lib/systemd/coredump/*
	-rw------- 1 opendkim postfix-milter 26M Oct 31 19:44 /var/lib/systemd/coredump/core.3557
gdb /usr/local/opendkim/sbin/opendkim /var/lib/systemd/coredump/core.3557
	...
	[Thread debugging using libthread_db enabled]
	Using host libthread_db library "/lib64/libthread_db.so.1".
	Core was generated by `/usr/local/opendkim/sbin/opendkim -l -x /usr/local/etc/opendkim/opendkim.conf -'.
	Program terminated with signal SIGABRT, Aborted.
	#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
	51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
	--Type <RET> for more, q to quit, c to continue without paging--c
	[Current thread is 1 (Thread 0x7fe2deafe700 (LWP 3685))]
	(gdb)  thread apply all bt f

	Thread 4 (Thread 0x7fe2dfb00700 (LWP 3558)):
	#0  do_sigwait (set=<optimized out>, set@entry=0x7fe2dfaffe70, sig=sig@entry=0x7fe2dfaffefc)
	    at ../sysdeps/unix/sysv/linux/sigwait.c:64
	        ret = <optimized out>
	        tmpset = {__val = {0 <repeats 16 times>}}
	        __mask = <optimized out>
	        __word = <optimized out>
	        __mask = <optimized out>
	        __word = <optimized out>
	#1  0x00007fe2e0a84e6d in __sigwait (set=0x7fe2dfaffe70, sig=0x7fe2dfaffefc)
	    at ../sysdeps/unix/sysv/linux/sigwait.c:96
	        oldtype = 0
	        result = <optimized out>
	        sig = 0x7fe2dfaffefc
	        set = 0x7fe2dfaffe70
	        oldtype = <optimized out>
	        result = <optimized out>
	        oldtype = <optimized out>
	--Type <RET> for more, q to quit, c to continue without paging--c
	        result = <optimized out>
	#2  0x00000000004083e4 in dkimf_reloader ()
	No symbol table info available.
	#3  0x00007fe2e0a7a559 in start_thread (arg=0x7fe2dfb00700) at pthread_create.c:465
	        pd = 0x7fe2dfb00700
	        now = <optimized out>
	        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140612392191744, 481145786195812320, 140723795460766, 140723795460767, 0, 140723795460768, -474882555636572192, -474955194474389536}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
	        not_first_call = <optimized out>
	        pagesize_m1 = <optimized out>
	        sp = <optimized out>
	        freesize = <optimized out>
	        __PRETTY_FUNCTION__ = "start_thread"
	        frame = <optimized out>
	#4  0x00007fe2e07b181f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
	No locals.

	Thread 3 (Thread 0x7fe2df2ff700 (LWP 3559)):
	#0  do_sigwait (set=<optimized out>, set@entry=0x7fe2df2fee70, sig=sig@entry=0x7fe2df2fee6c) at ../sysdeps/unix/sysv/linux/sigwait.c:64
	        ret = <optimized out>
	        tmpset = {__val = {0 <repeats 16 times>}}
	        __mask = <optimized out>
	        __word = <optimized out>
	        __mask = <optimized out>
	        __word = <optimized out>
	#1  0x00007fe2e0a84e6d in __sigwait (set=0x7fe2df2fee70, sig=0x7fe2df2fee6c) at ../sysdeps/unix/sysv/linux/sigwait.c:96
	        oldtype = 0
	        result = <optimized out>
	        sig = 0x7fe2df2fee6c
	        set = 0x7fe2df2fee70
	        oldtype = <optimized out>
	        result = <optimized out>
	        oldtype = <optimized out>
	        result = <optimized out>
	#2  0x000000000042817c in mi_signal_thread ()
	No symbol table info available.
	#3  0x00007fe2e0a7a559 in start_thread (arg=0x7fe2df2ff700) at pthread_create.c:465
	        pd = 0x7fe2df2ff700
	        now = <optimized out>
	        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140612383799040, 481145786195812320, 140723795460590, 140723795460591, 34314032, 140723795460592, -474881456661815328, -474955194474389536}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
	        not_first_call = <optimized out>
	        pagesize_m1 = <optimized out>
	        sp = <optimized out>
	        freesize = <optimized out>
	        __PRETTY_FUNCTION__ = "start_thread"
	        frame = <optimized out>
	#4  0x00007fe2e07b181f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
	No locals.

	Thread 2 (Thread 0x7fe2e31e1740 (LWP 3557)):
	#0  0x00007fe2e07a8ef3 in __GI___select (nfds=5, readfds=0x7ffccfd70150, writefds=0x0, exceptfds=0x7ffccfd701d0, timeout=0x7ffccfd70140) at ../sysdeps/unix/sysv/linux/select.c:41
	        resultvar = 18446744073709551102
	        sc_cancel_oldtype = 0
	        sc_ret = <optimized out>
	#1  0x000000000042680f in mi_listener ()
	No symbol table info available.
	#2  0x0000000000425c4e in smfi_main ()
	No symbol table info available.
	#3  0x000000000041a9f1 in main ()
	No symbol table info available.

	Thread 1 (Thread 0x7fe2deafe700 (LWP 3685)):
	#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
	        set = {__val = {16899, 140612443250784, 0, 3, 4294967294, 0, 140612375403904, 140612447740531, 5, 0, 0, 140612404552712, 140612375403840, 140612447770602, 140612263398208, 0}}
	        pid = <optimized out>
	        tid = <optimized out>
	        ret = <optimized out>
	#1  0x00007fe2e06f06c1 in __GI_abort () at abort.c:79
	        save_stage = 1
	        act = {__sigaction_handler = {sa_handler = 0x64203b646578616c, sa_sigaction = 0x64203b646578616c}, sa_mask = {__val = {8032016439431360573, 3760898644827779385, 4051325634811748657, 3762248639015107960, 7064188739919425589, 8675461341612877096, 44965372020, 0, 0, 2, 2, 1, 0, 4, 140612375403424, 140612375404032}}, sa_flags = -558900320, sa_restorer = 0x1000}
	        sigs = {__val = {32, 0 <repeats 15 times>}}
	#2  0x00007fe2e0732427 in __libc_message (action=action@entry=(do_abort | do_backtrace), fmt=fmt@entry=0x7fe2e083b210 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:181
	        ap = {{gp_offset = 40, fp_offset = 32738, overflow_arg_area = 0x7fe2deafde10, reg_save_area = 0x7fe2deafdda0}}
	        fd = <optimized out>
	        list = <optimized out>
	        nlist = <optimized out>
	        cp = <optimized out>
	        written = <optimized out>
	#3  0x00007fe2e0738c43 in malloc_printerr (action=<optimized out>, str=0x7fe2e083b598 "double free or corruption (out)", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5428
	        buf = "00007fe2d802cc40"
	        cp = <optimized out>
	        ar_ptr = <optimized out>
	        ptr = <optimized out>
	        str = 0x7fe2e083b598 "double free or corruption (out)"
	        action = <optimized out>
	        buf = <optimized out>
	        cp = <optimized out>
	#4  0x00007fe2e073a549 in _int_free (av=0x7fe2e0a6dc20 <main_arena>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4170
	        size = <optimized out>
	        fb = <optimized out>
	        nextchunk = <optimized out>
	        nextsize = <optimized out>
	        nextinuse = <optimized out>
	        prevsize = <optimized out>
	        bck = <optimized out>
	        fwd = <optimized out>
	        errstr = <optimized out>
	        locked = <optimized out>
	        __func__ = "_int_free"
	#5  0x00007fe2e081f5fb in tcache_thread_freeres () at malloc.c:2999
	        e = <optimized out>
	        i = <optimized out>
	        tcache_tmp = 0x7fe2d80008c0
	#6  0x00007fe2e081f652 in __libc_thread_freeres () at thread-freeres.c:29
	        ptr = 0x7fe2e0a698b8 <__elf_set___libc_thread_subfreeres_element_tcache_thread_freeres__>
	#7  0x00007fe2e0a7a57e in start_thread (arg=0x7fe2deafe700) at pthread_create.c:478
	        pd = 0x7fe2deafe700
	        now = <optimized out>
	        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140612375406336, 481145786195812320, 140723795460238, 140723795460239, 34456544, 140723795460240, -474880357687058464, -474955194474389536}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
	        not_first_call = <optimized out>
	        pagesize_m1 = <optimized out>
	        sp = <optimized out>
	        freesize = <optimized out>
	        __PRETTY_FUNCTION__ = "start_thread"
	        frame = <optimized out>
	#8  0x00007fe2e07b181f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
	No locals
```
